# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    build: ./postgress
    restart: always
    env_file: ./.env
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build: ./ser_node
    env_file: ./.env
    environment:
      - DB_HOST=db
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    command: /bin/sh -c "node index.js && tail -f /dev/null"
  #   volumes:
  #     - $LOG_FILE_PATH/log:/node-app/app/log
